    const CourseData = [
        {
            id:1,
            img: 'https://picsum.photos/200',
            title: 'Course 1',
            category: 'Web Development',
            level: 'Beginner',
            author: 'Cédric Ananga',
            desc: 'This is course 1',
            followers: 45,
            module: [
                {
                  id: 1,
                  title: 'Module 1: Lorem ipsum',
                  chapters: [
                    {
                      id: 1,
                      title: 'Chapter 1: Introduction',
                      summary: 'Lorem ipsum',
                      url: 'assets/videos/free-courses-with-free-certificates.mp4',
                      read:false,
                      exercise: [
                        {
                          id: 1,
                          title: 'Exercise 1',
                          question1:'Lorem ipsum dolor?',
                          answer1: 'Lorem ipsum',
                          question2:'Lorem ipsum dolor?',
                          answer2: 'Lorem ipsum',
                          question3:'Lorem ipsum dolor?',
                          answer3: 'Lorem ipsum',
                          question4:'Lorem ipsum dolor?',
                          answer4: 'Lorem ipsum',
                          question5:'Lorem ipsum dolor?',
                          answer5: 'Lorem ipsum',
                        },
                      ],
                    },
                    {
                      id: 2,
                      title: 'Chapter 2: Lorem ipsum',
                      summary: 'Lorem ipsum dolor',
                      url: 'assets/videos/free-courses-with-free-certificates.mp4',
                      read:false,
                      exercise: [
                        {
                          id: 1,
                          title: 'Exercise 1',
                          question1:'Lorem ipsum dolor?',
                          answer1: 'Lorem ipsum',
                          question2:'Lorem ipsum dolor?',
                          answer2: 'Lorem ipsum',
                          question3:'Lorem ipsum dolor?',
                          answer3: 'Lorem ipsum',
                          question4:'Lorem ipsum dolor?',
                          answer4: 'Lorem ipsum',
                          question5:'Lorem ipsum dolor?',
                          answer5: 'Lorem ipsum',
                        },
                      ],
                    },
                    {
                        id: 3,
                        title: 'Chapter 3: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                  ],
                },
                {
                    id: 2,
                    title: 'Module 2: Lorem ipsum',
                    chapters: [
                      {
                        id: 4,
                        title: 'Chapter 4: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                      {
                        id: 5,
                        title: 'Chapter 5: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                      {
                          id: 6,
                          title: 'Chapter 6: Lorem ipsum',
                          summary: 'Lorem ipsum dolor',
                          url: 'assets/videos/free-courses-with-free-certificates.mp4',
                          read:false,
                          exercise: [
                            {
                              id: 1,
                              title: 'Exercise 1',
                              question1:'Lorem ipsum dolor?',
                              answer1: 'Lorem ipsum',
                              question2:'Lorem ipsum dolor?',
                              answer2: 'Lorem ipsum',
                              question3:'Lorem ipsum dolor?',
                              answer3: 'Lorem ipsum',
                              question4:'Lorem ipsum dolor?',
                              answer4: 'Lorem ipsum',
                              question5:'Lorem ipsum dolor?',
                              answer5: 'Lorem ipsum',
                            },
                          ],
                        },
                    ],
                  },
                  {
                    id: 3,
                    title: 'Module 3: Lorem ipsum',
                    chapters: [
                      {
                        id: 7,
                        title: 'Chapter 7: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                      {
                        id: 8,
                        title: 'Chapter 8: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                    ],
                  },
            ]
        },
        {
            id:2,
            img: 'https://picsum.photos/200',
            title: 'Course 2',
            category: 'Gaming',
            level: 'Intermediate',
            author: 'Cédric Ananga',
            desc: 'This is course 2',
            followers: 10,
            module: [
                {
                  id: 1,
                  title: 'Module 1: Lorem ipsum',
                  chapters: [
                    {
                      id: 1,
                      title: 'Chapter 1: Introduction',
                      summary: 'Lorem ipsum',
                      url: 'assets/videos/free-courses-with-free-certificates.mp4',
                      read:false,
                      exercise: [
                        {
                          id: 1,
                          title: 'Exercise 1',
                          question1:'Lorem ipsum dolor?',
                          answer1: 'Lorem ipsum',
                          question2:'Lorem ipsum dolor?',
                          answer2: 'Lorem ipsum',
                          question3:'Lorem ipsum dolor?',
                          answer3: 'Lorem ipsum',
                          question4:'Lorem ipsum dolor?',
                          answer4: 'Lorem ipsum',
                          question5:'Lorem ipsum dolor?',
                          answer5: 'Lorem ipsum',
                        },
                      ],
                    },
                    {
                      id: 2,
                      title: 'Chapter 2: Lorem ipsum',
                      summary: 'Lorem ipsum dolor',
                      url: 'assets/videos/free-courses-with-free-certificates.mp4',
                      read:false,
                      exercise: [
                        {
                          id: 1,
                          title: 'Exercise 1',
                          question1:'Lorem ipsum dolor?',
                          answer1: 'Lorem ipsum',
                          question2:'Lorem ipsum dolor?',
                          answer2: 'Lorem ipsum',
                          question3:'Lorem ipsum dolor?',
                          answer3: 'Lorem ipsum',
                          question4:'Lorem ipsum dolor?',
                          answer4: 'Lorem ipsum',
                          question5:'Lorem ipsum dolor?',
                          answer5: 'Lorem ipsum',
                        },
                      ],
                    },
                    {
                        id: 3,
                        title: 'Chapter 3: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                  ],
                },
                {
                    id: 2,
                    title: 'Module 2: Lorem ipsum',
                    chapters: [
                      {
                        id: 4,
                        title: 'Chapter 4: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                      {
                        id: 5,
                        title: 'Chapter 5: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                      {
                          id: 6,
                          title: 'Chapter 6: Lorem ipsum',
                          summary: 'Lorem ipsum dolor',
                          url: 'assets/videos/free-courses-with-free-certificates.mp4',
                          read:false,
                          exercise: [
                            {
                              id: 1,
                              title: 'Exercise 1',
                              question1:'Lorem ipsum dolor?',
                              answer1: 'Lorem ipsum',
                              question2:'Lorem ipsum dolor?',
                              answer2: 'Lorem ipsum',
                              question3:'Lorem ipsum dolor?',
                              answer3: 'Lorem ipsum',
                              question4:'Lorem ipsum dolor?',
                              answer4: 'Lorem ipsum',
                              question5:'Lorem ipsum dolor?',
                              answer5: 'Lorem ipsum',
                            },
                          ],
                        },
                    ],
                  },
                  {
                    id: 3,
                    title: 'Module 3: Lorem ipsum',
                    chapters: [
                      {
                        id: 7,
                        title: 'Chapter 7: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                      {
                        id: 8,
                        title: 'Chapter 8: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                    ],
                },
            ]
        },
        {
            id:3,
            img: 'https://picsum.photos/200',
            title: 'Course 3',
            category: 'Design',
            author: 'Bernard Arnaud',
            level: 'Advanced',
            desc: 'This is course 3',
            followers: 50,
            module: [
                {
                  id: 1,
                  title: 'Module 1: Lorem ipsum',
                  chapters: [
                    {
                      id: 1,
                      title: 'Chapter 1: Introduction',
                      summary: 'Lorem ipsum',
                      url: 'assets/videos/free-courses-with-free-certificates.mp4',
                      read:false,
                      exercise: [
                        {
                          id: 1,
                          title: 'Exercise 1',
                          question1:'Lorem ipsum dolor?',
                          answer1: 'Lorem ipsum',
                          question2:'Lorem ipsum dolor?',
                          answer2: 'Lorem ipsum',
                          question3:'Lorem ipsum dolor?',
                          answer3: 'Lorem ipsum',
                          question4:'Lorem ipsum dolor?',
                          answer4: 'Lorem ipsum',
                          question5:'Lorem ipsum dolor?',
                          answer5: 'Lorem ipsum',
                        },
                      ],
                    },
                    {
                      id: 2,
                      title: 'Chapter 2: Lorem ipsum',
                      summary: 'Lorem ipsum dolor',
                      url: 'assets/videos/free-courses-with-free-certificates.mp4',
                      read:false,
                      exercise: [
                        {
                          id: 1,
                          title: 'Exercise 1',
                          question1:'Lorem ipsum dolor?',
                          answer1: 'Lorem ipsum',
                          question2:'Lorem ipsum dolor?',
                          answer2: 'Lorem ipsum',
                          question3:'Lorem ipsum dolor?',
                          answer3: 'Lorem ipsum',
                          question4:'Lorem ipsum dolor?',
                          answer4: 'Lorem ipsum',
                          question5:'Lorem ipsum dolor?',
                          answer5: 'Lorem ipsum',
                        },
                      ],
                    },
                    {
                        id: 3,
                        title: 'Chapter 3: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                  ],
                },
                {
                    id: 2,
                    title: 'Module 2: Lorem ipsum',
                    chapters: [
                      {
                        id: 4,
                        title: 'Chapter 4: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                      {
                        id: 5,
                        title: 'Chapter 5: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                      {
                          id: 6,
                          title: 'Chapter 6: Lorem ipsum',
                          summary: 'Lorem ipsum dolor',
                          url: 'assets/videos/free-courses-with-free-certificates.mp4',
                          read:false,
                          exercise: [
                            {
                              id: 1,
                              title: 'Exercise 1',
                              question1:'Lorem ipsum dolor?',
                              answer1: 'Lorem ipsum',
                              question2:'Lorem ipsum dolor?',
                              answer2: 'Lorem ipsum',
                              question3:'Lorem ipsum dolor?',
                              answer3: 'Lorem ipsum',
                              question4:'Lorem ipsum dolor?',
                              answer4: 'Lorem ipsum',
                              question5:'Lorem ipsum dolor?',
                              answer5: 'Lorem ipsum',
                            },
                          ],
                        },
                    ],
                  },
                  {
                    id: 3,
                    title: 'Module 3: Lorem ipsum',
                    chapters: [
                      {
                        id: 7,
                        title: 'Chapter 7: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                      {
                        id: 8,
                        title: 'Chapter 8: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                    ],
                },
            ]  
        },
        {
            id:4,
            img: 'https://picsum.photos/200',
            title: 'Course 4',
            category: 'Web Development',
            author: 'Jeff Bezos',
            level: 'Beginner',
            desc: 'This is course 4',
            followers: 19,
            module: [
                {
                  id: 1,
                  title: 'Module 1: Lorem ipsum',
                  chapters: [
                    {
                      id: 1,
                      title: 'Chapter 1: Introduction',
                      summary: 'Lorem ipsum',
                      url: 'assets/videos/free-courses-with-free-certificates.mp4',
                      read:false,
                      exercise: [
                        {
                          id: 1,
                          title: 'Exercise 1',
                          question1:'Lorem ipsum dolor?',
                          answer1: 'Lorem ipsum',
                          question2:'Lorem ipsum dolor?',
                          answer2: 'Lorem ipsum',
                          question3:'Lorem ipsum dolor?',
                          answer3: 'Lorem ipsum',
                          question4:'Lorem ipsum dolor?',
                          answer4: 'Lorem ipsum',
                          question5:'Lorem ipsum dolor?',
                          answer5: 'Lorem ipsum',
                        },
                      ],
                    },
                    {
                      id: 2,
                      title: 'Chapter 2: Lorem ipsum',
                      summary: 'Lorem ipsum dolor',
                      url: 'assets/videos/free-courses-with-free-certificates.mp4',
                      read:false,
                      exercise: [
                        {
                          id: 1,
                          title: 'Exercise 1',
                          question1:'Lorem ipsum dolor?',
                          answer1: 'Lorem ipsum',
                          question2:'Lorem ipsum dolor?',
                          answer2: 'Lorem ipsum',
                          question3:'Lorem ipsum dolor?',
                          answer3: 'Lorem ipsum',
                          question4:'Lorem ipsum dolor?',
                          answer4: 'Lorem ipsum',
                          question5:'Lorem ipsum dolor?',
                          answer5: 'Lorem ipsum',
                        },
                      ],
                    },
                    {
                        id: 3,
                        title: 'Chapter 3: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                  ],
                },
                {
                    id: 2,
                    title: 'Module 2: Lorem ipsum',
                    chapters: [
                      {
                        id: 4,
                        title: 'Chapter 4: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                      {
                        id: 5,
                        title: 'Chapter 5: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                      {
                          id: 6,
                          title: 'Chapter 6: Lorem ipsum',
                          summary: 'Lorem ipsum dolor',
                          url: 'assets/videos/free-courses-with-free-certificates.mp4',
                          read:false,
                          exercise: [
                            {
                              id: 1,
                              title: 'Exercise 1',
                              question1:'Lorem ipsum dolor?',
                              answer1: 'Lorem ipsum',
                              question2:'Lorem ipsum dolor?',
                              answer2: 'Lorem ipsum',
                              question3:'Lorem ipsum dolor?',
                              answer3: 'Lorem ipsum',
                              question4:'Lorem ipsum dolor?',
                              answer4: 'Lorem ipsum',
                              question5:'Lorem ipsum dolor?',
                              answer5: 'Lorem ipsum',
                            },
                          ],
                        },
                    ],
                  },
                  {
                    id: 3,
                    title: 'Module 3: Lorem ipsum',
                    chapters: [
                      {
                        id: 7,
                        title: 'Chapter 7: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                      {
                        id: 8,
                        title: 'Chapter 8: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                    ],
                },
            ]
        },
        {
            id:5,
            img: 'https://picsum.photos/200',
            title: 'Course 5',
            category: 'Gaming',
            author: 'Ellon Musk',
            level: 'Intermediate',
            desc: 'This is course 5',
            followers: 27,
            module: [
                {
                  id: 1,
                  title: 'Module 1: Lorem ipsum',
                  chapters: [
                    {
                      id: 1,
                      title: 'Chapter 1: Introduction',
                      summary: 'Lorem ipsum',
                      url: 'assets/videos/free-courses-with-free-certificates.mp4',
                      read:false,
                      exercise: [
                        {
                          id: 1,
                          title: 'Exercise 1',
                          question1:'Lorem ipsum dolor?',
                          answer1: 'Lorem ipsum',
                          question2:'Lorem ipsum dolor?',
                          answer2: 'Lorem ipsum',
                          question3:'Lorem ipsum dolor?',
                          answer3: 'Lorem ipsum',
                          question4:'Lorem ipsum dolor?',
                          answer4: 'Lorem ipsum',
                          question5:'Lorem ipsum dolor?',
                          answer5: 'Lorem ipsum',
                        },
                      ],
                    },
                    {
                      id: 2,
                      title: 'Chapter 2: Lorem ipsum',
                      summary: 'Lorem ipsum dolor',
                      url: 'assets/videos/free-courses-with-free-certificates.mp4',
                      read:false,
                      exercise: [
                        {
                          id: 1,
                          title: 'Exercise 1',
                          question1:'Lorem ipsum dolor?',
                          answer1: 'Lorem ipsum',
                          question2:'Lorem ipsum dolor?',
                          answer2: 'Lorem ipsum',
                          question3:'Lorem ipsum dolor?',
                          answer3: 'Lorem ipsum',
                          question4:'Lorem ipsum dolor?',
                          answer4: 'Lorem ipsum',
                          question5:'Lorem ipsum dolor?',
                          answer5: 'Lorem ipsum',
                        },
                      ],
                    },
                    {
                        id: 3,
                        title: 'Chapter 3: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                  ],
                },
                {
                    id: 2,
                    title: 'Module 2: Lorem ipsum',
                    chapters: [
                      {
                        id: 4,
                        title: 'Chapter 4: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                      {
                        id: 5,
                        title: 'Chapter 5: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                      {
                          id: 6,
                          title: 'Chapter 6: Lorem ipsum',
                          summary: 'Lorem ipsum dolor',
                          url: 'assets/videos/free-courses-with-free-certificates.mp4',
                          read:false,
                          exercise: [
                            {
                              id: 1,
                              title: 'Exercise 1',
                              question1:'Lorem ipsum dolor?',
                              answer1: 'Lorem ipsum',
                              question2:'Lorem ipsum dolor?',
                              answer2: 'Lorem ipsum',
                              question3:'Lorem ipsum dolor?',
                              answer3: 'Lorem ipsum',
                              question4:'Lorem ipsum dolor?',
                              answer4: 'Lorem ipsum',
                              question5:'Lorem ipsum dolor?',
                              answer5: 'Lorem ipsum',
                            },
                          ],
                        },
                    ],
                  },
                  {
                    id: 3,
                    title: 'Module 3: Lorem ipsum',
                    chapters: [
                      {
                        id: 7,
                        title: 'Chapter 7: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                      {
                        id: 8,
                        title: 'Chapter 8: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                    ],
                  },
                ]
        },
        {
            id:6,
            img: 'https://picsum.photos/200',
            title: 'Course 6',
            category: 'Design',
            author: 'Mark Zuckergberg',
            level: 'Advanced',
            desc: 'This is course 6',
            followers: 58,
            module: [
                {
                  id: 1,
                  title: 'Module 1: Lorem ipsum',
                  chapters: [
                    {
                      id: 1,
                      title: 'Chapter 1: Introduction',
                      summary: 'Lorem ipsum',
                      url: 'assets/videos/free-courses-with-free-certificates.mp4',
                      read:false,
                      exercise: [
                        {
                          id: 1,
                          title: 'Exercise 1',
                          question1:'Lorem ipsum dolor?',
                          answer1: 'Lorem ipsum',
                          question2:'Lorem ipsum dolor?',
                          answer2: 'Lorem ipsum',
                          question3:'Lorem ipsum dolor?',
                          answer3: 'Lorem ipsum',
                          question4:'Lorem ipsum dolor?',
                          answer4: 'Lorem ipsum',
                          question5:'Lorem ipsum dolor?',
                          answer5: 'Lorem ipsum',
                        },
                      ],
                    },
                    {
                      id: 2,
                      title: 'Chapter 2: Lorem ipsum',
                      summary: 'Lorem ipsum dolor',
                      url: 'assets/videos/free-courses-with-free-certificates.mp4',
                      read:false,
                      exercise: [
                        {
                          id: 1,
                          title: 'Exercise 1',
                          question1:'Lorem ipsum dolor?',
                          answer1: 'Lorem ipsum',
                          question2:'Lorem ipsum dolor?',
                          answer2: 'Lorem ipsum',
                          question3:'Lorem ipsum dolor?',
                          answer3: 'Lorem ipsum',
                          question4:'Lorem ipsum dolor?',
                          answer4: 'Lorem ipsum',
                          question5:'Lorem ipsum dolor?',
                          answer5: 'Lorem ipsum',
                        },
                      ],
                    },
                    {
                        id: 3,
                        title: 'Chapter 3: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                  ],
                },
                {
                    id: 2,
                    title: 'Module 2: Lorem ipsum',
                    chapters: [
                      {
                        id: 4,
                        title: 'Chapter 4: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                      {
                        id: 5,
                        title: 'Chapter 5: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                      {
                          id: 6,
                          title: 'Chapter 6: Lorem ipsum',
                          summary: 'Lorem ipsum dolor',
                          url: 'assets/videos/free-courses-with-free-certificates.mp4',
                          read:false,
                          exercise: [
                            {
                              id: 1,
                              title: 'Exercise 1',
                              question1:'Lorem ipsum dolor?',
                              answer1: 'Lorem ipsum',
                              question2:'Lorem ipsum dolor?',
                              answer2: 'Lorem ipsum',
                              question3:'Lorem ipsum dolor?',
                              answer3: 'Lorem ipsum',
                              question4:'Lorem ipsum dolor?',
                              answer4: 'Lorem ipsum',
                              question5:'Lorem ipsum dolor?',
                              answer5: 'Lorem ipsum',
                            },
                          ],
                        },
                    ],
                  },
                  {
                    id: 3,
                    title: 'Module 3: Lorem ipsum',
                    chapters: [
                      {
                        id: 7,
                        title: 'Chapter 7: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                      {
                        id: 8,
                        title: 'Chapter 8: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                    ],
                  },
           ]
        },
        {
            id:7,
            img: 'https://picsum.photos/200',
            title: 'Course 7',
            category: 'Web Development',
            author: 'Bernard Arnaud',
            level: 'Beginner',
            desc: 'This is course 7',
            followers: 62,
            module: [
                {
                  id: 1,
                  title: 'Module 1: Lorem ipsum',
                  chapters: [
                    {
                      id: 1,
                      title: 'Chapter 1: Introduction',
                      summary: 'Lorem ipsum',
                      url: 'assets/videos/free-courses-with-free-certificates.mp4',
                      read:false,
                      exercise: [
                        {
                          id: 1,
                          title: 'Exercise 1',
                          question1:'Lorem ipsum dolor?',
                          answer1: 'Lorem ipsum',
                          question2:'Lorem ipsum dolor?',
                          answer2: 'Lorem ipsum',
                          question3:'Lorem ipsum dolor?',
                          answer3: 'Lorem ipsum',
                          question4:'Lorem ipsum dolor?',
                          answer4: 'Lorem ipsum',
                          question5:'Lorem ipsum dolor?',
                          answer5: 'Lorem ipsum',
                        },
                      ],
                    },
                    {
                      id: 2,
                      title: 'Chapter 2: Lorem ipsum',
                      summary: 'Lorem ipsum dolor',
                      url: 'assets/videos/free-courses-with-free-certificates.mp4',
                      read:false,
                      exercise: [
                        {
                          id: 1,
                          title: 'Exercise 1',
                          question1:'Lorem ipsum dolor?',
                          answer1: 'Lorem ipsum',
                          question2:'Lorem ipsum dolor?',
                          answer2: 'Lorem ipsum',
                          question3:'Lorem ipsum dolor?',
                          answer3: 'Lorem ipsum',
                          question4:'Lorem ipsum dolor?',
                          answer4: 'Lorem ipsum',
                          question5:'Lorem ipsum dolor?',
                          answer5: 'Lorem ipsum',
                        },
                      ],
                    },
                    {
                        id: 3,
                        title: 'Chapter 3: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                  ],
                },
                {
                    id: 2,
                    title: 'Module 2: Lorem ipsum',
                    chapters: [
                      {
                        id: 4,
                        title: 'Chapter 4: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                      {
                        id: 5,
                        title: 'Chapter 5: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                      {
                          id: 6,
                          title: 'Chapter 6: Lorem ipsum',
                          summary: 'Lorem ipsum dolor',
                          url: 'assets/videos/free-courses-with-free-certificates.mp4',
                          read:false,
                          exercise: [
                            {
                              id: 1,
                              title: 'Exercise 1',
                              question1:'Lorem ipsum dolor?',
                              answer1: 'Lorem ipsum',
                              question2:'Lorem ipsum dolor?',
                              answer2: 'Lorem ipsum',
                              question3:'Lorem ipsum dolor?',
                              answer3: 'Lorem ipsum',
                              question4:'Lorem ipsum dolor?',
                              answer4: 'Lorem ipsum',
                              question5:'Lorem ipsum dolor?',
                              answer5: 'Lorem ipsum',
                            },
                          ],
                        },
                    ],
                  },
                  {
                    id: 3,
                    title: 'Module 3: Lorem ipsum',
                    chapters: [
                      {
                        id: 7,
                        title: 'Chapter 7: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                      {
                        id: 8,
                        title: 'Chapter 8: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                    ],
                  },
                ]
        },
        {
            id:8,
            img: 'https://picsum.photos/200',
            title: 'Course 8',
            category: 'Gaming',
            author: 'Sergei Brinn',
            level:'Intermediate',
            desc: 'This is course 8',
            followers: 13,
            module: [
                {
                  id: 1,
                  title: 'Module 1: Lorem ipsum',
                  chapters: [
                    {
                      id: 1,
                      title: 'Chapter 1: Introduction',
                      summary: 'Lorem ipsum',
                      url: 'assets/videos/free-courses-with-free-certificates.mp4',
                      read:false,
                      exercise: [
                        {
                          id: 1,
                          title: 'Exercise 1',
                          question1:'Lorem ipsum dolor?',
                          answer1: 'Lorem ipsum',
                          question2:'Lorem ipsum dolor?',
                          answer2: 'Lorem ipsum',
                          question3:'Lorem ipsum dolor?',
                          answer3: 'Lorem ipsum',
                          question4:'Lorem ipsum dolor?',
                          answer4: 'Lorem ipsum',
                          question5:'Lorem ipsum dolor?',
                          answer5: 'Lorem ipsum',
                        },
                      ],
                    },
                    {
                      id: 2,
                      title: 'Chapter 2: Lorem ipsum',
                      summary: 'Lorem ipsum dolor',
                      url: 'assets/videos/free-courses-with-free-certificates.mp4',
                      read:false,
                      exercise: [
                        {
                          id: 1,
                          title: 'Exercise 1',
                          question1:'Lorem ipsum dolor?',
                          answer1: 'Lorem ipsum',
                          question2:'Lorem ipsum dolor?',
                          answer2: 'Lorem ipsum',
                          question3:'Lorem ipsum dolor?',
                          answer3: 'Lorem ipsum',
                          question4:'Lorem ipsum dolor?',
                          answer4: 'Lorem ipsum',
                          question5:'Lorem ipsum dolor?',
                          answer5: 'Lorem ipsum',
                        },
                      ],
                    },
                    {
                        id: 3,
                        title: 'Chapter 3: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                  ],
                },
                {
                    id: 2,
                    title: 'Module 2: Lorem ipsum',
                    chapters: [
                      {
                        id: 4,
                        title: 'Chapter 4: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                      {
                        id: 5,
                        title: 'Chapter 5: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                      {
                          id: 6,
                          title: 'Chapter 6: Lorem ipsum',
                          summary: 'Lorem ipsum dolor',
                          url: 'assets/videos/free-courses-with-free-certificates.mp4',
                          read:false,
                          exercise: [
                            {
                              id: 1,
                              title: 'Exercise 1',
                              question1:'Lorem ipsum dolor?',
                              answer1: 'Lorem ipsum',
                              question2:'Lorem ipsum dolor?',
                              answer2: 'Lorem ipsum',
                              question3:'Lorem ipsum dolor?',
                              answer3: 'Lorem ipsum',
                              question4:'Lorem ipsum dolor?',
                              answer4: 'Lorem ipsum',
                              question5:'Lorem ipsum dolor?',
                              answer5: 'Lorem ipsum',
                            },
                          ],
                        },
                    ],
                  },
                  {
                    id: 3,
                    title: 'Module 3: Lorem ipsum',
                    chapters: [
                      {
                        id: 7,
                        title: 'Chapter 7: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                      {
                        id: 8,
                        title: 'Chapter 8: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                    ],
                  },
           ]
        },
        {
            id:9,
            img: 'https://picsum.photos/200',
            title: 'Course 9',
            category: 'Design',
            author: 'Lary Page',
            level: 'Advanced',
            desc: 'This is course 9',
            followers: 23,
            module: [
                {
                  id: 1,
                  title: 'Module 1: Lorem ipsum',
                  chapters: [
                    {
                      id: 1,
                      title: 'Chapter 1: Introduction',
                      summary: 'Lorem ipsum',
                      url: 'assets/videos/free-courses-with-free-certificates.mp4',
                      read:false,
                      exercise: [
                        {
                          id: 1,
                          title: 'Exercise 1',
                          question1:'Lorem ipsum dolor?',
                          answer1: 'Lorem ipsum',
                          question2:'Lorem ipsum dolor?',
                          answer2: 'Lorem ipsum',
                          question3:'Lorem ipsum dolor?',
                          answer3: 'Lorem ipsum',
                          question4:'Lorem ipsum dolor?',
                          answer4: 'Lorem ipsum',
                          question5:'Lorem ipsum dolor?',
                          answer5: 'Lorem ipsum',
                        },
                      ],
                    },
                    {
                      id: 2,
                      title: 'Chapter 2: Lorem ipsum',
                      summary: 'Lorem ipsum dolor',
                      url: 'assets/videos/free-courses-with-free-certificates.mp4',
                      read:false,
                      exercise: [
                        {
                          id: 1,
                          title: 'Exercise 1',
                          question1:'Lorem ipsum dolor?',
                          answer1: 'Lorem ipsum',
                          question2:'Lorem ipsum dolor?',
                          answer2: 'Lorem ipsum',
                          question3:'Lorem ipsum dolor?',
                          answer3: 'Lorem ipsum',
                          question4:'Lorem ipsum dolor?',
                          answer4: 'Lorem ipsum',
                          question5:'Lorem ipsum dolor?',
                          answer5: 'Lorem ipsum',
                        },
                      ],
                    },
                    {
                        id: 3,
                        title: 'Chapter 3: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                  ],
                },
                {
                    id: 2,
                    title: 'Module 2: Lorem ipsum',
                    chapters: [
                      {
                        id: 4,
                        title: 'Chapter 4: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                      {
                        id: 5,
                        title: 'Chapter 5: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                      {
                          id: 6,
                          title: 'Chapter 6: Lorem ipsum',
                          summary: 'Lorem ipsum dolor',
                          url: 'assets/videos/free-courses-with-free-certificates.mp4',
                          read:false,
                          exercise: [
                            {
                              id: 1,
                              title: 'Exercise 1',
                              question1:'Lorem ipsum dolor?',
                              answer1: 'Lorem ipsum',
                              question2:'Lorem ipsum dolor?',
                              answer2: 'Lorem ipsum',
                              question3:'Lorem ipsum dolor?',
                              answer3: 'Lorem ipsum',
                              question4:'Lorem ipsum dolor?',
                              answer4: 'Lorem ipsum',
                              question5:'Lorem ipsum dolor?',
                              answer5: 'Lorem ipsum',
                            },
                          ],
                        },
                    ],
                  },
                  {
                    id: 3,
                    title: 'Module 3: Lorem ipsum',
                    chapters: [
                      {
                        id: 7,
                        title: 'Chapter 7: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                      {
                        id: 8,
                        title: 'Chapter 8: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                    ],
                  },
           ]
        },
        {
            id:10,
            img: 'https://picsum.photos/200',
            title: 'Course 10',
            category: 'Web Development',
            author: 'Jeff Bezos',
            level: 'Beginner',
            desc: 'This is course 10',
            followers: 105,
            module: [
                {
                  id: 1,
                  title: 'Module 1: Lorem ipsum',
                  chapters: [
                    {
                      id: 1,
                      title: 'Chapter 1: Introduction',
                      summary: 'Lorem ipsum',
                      url: 'assets/videos/free-courses-with-free-certificates.mp4',
                      read:false,
                      exercise: [
                        {
                          id: 1,
                          title: 'Exercise 1',
                          question1:'Lorem ipsum dolor?',
                          answer1: 'Lorem ipsum',
                          question2:'Lorem ipsum dolor?',
                          answer2: 'Lorem ipsum',
                          question3:'Lorem ipsum dolor?',
                          answer3: 'Lorem ipsum',
                          question4:'Lorem ipsum dolor?',
                          answer4: 'Lorem ipsum',
                          question5:'Lorem ipsum dolor?',
                          answer5: 'Lorem ipsum',
                        },
                      ],
                    },
                    {
                      id: 2,
                      title: 'Chapter 2: Lorem ipsum',
                      summary: 'Lorem ipsum dolor',
                      url: 'assets/videos/free-courses-with-free-certificates.mp4',
                      read:false,
                      exercise: [
                        {
                          id: 1,
                          title: 'Exercise 1',
                          question1:'Lorem ipsum dolor?',
                          answer1: 'Lorem ipsum',
                          question2:'Lorem ipsum dolor?',
                          answer2: 'Lorem ipsum',
                          question3:'Lorem ipsum dolor?',
                          answer3: 'Lorem ipsum',
                          question4:'Lorem ipsum dolor?',
                          answer4: 'Lorem ipsum',
                          question5:'Lorem ipsum dolor?',
                          answer5: 'Lorem ipsum',
                        },
                      ],
                    },
                    {
                        id: 3,
                        title: 'Chapter 3: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                  ],
                },
                {
                    id: 2,
                    title: 'Module 2: Lorem ipsum',
                    chapters: [
                      {
                        id: 4,
                        title: 'Chapter 4: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                      {
                        id: 5,
                        title: 'Chapter 5: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                      {
                          id: 6,
                          title: 'Chapter 6: Lorem ipsum',
                          summary: 'Lorem ipsum dolor',
                          url: 'assets/videos/free-courses-with-free-certificates.mp4',
                          read:false,
                          exercise: [
                            {
                              id: 1,
                              title: 'Exercise 1',
                              question1:'Lorem ipsum dolor?',
                              answer1: 'Lorem ipsum',
                              question2:'Lorem ipsum dolor?',
                              answer2: 'Lorem ipsum',
                              question3:'Lorem ipsum dolor?',
                              answer3: 'Lorem ipsum',
                              question4:'Lorem ipsum dolor?',
                              answer4: 'Lorem ipsum',
                              question5:'Lorem ipsum dolor?',
                              answer5: 'Lorem ipsum',
                            },
                          ],
                        },
                    ],
                  },
                  {
                    id: 3,
                    title: 'Module 3: Lorem ipsum',
                    chapters: [
                      {
                        id: 7,
                        title: 'Chapter 7: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                      {
                        id: 8,
                        title: 'Chapter 8: Lorem ipsum',
                        summary: 'Lorem ipsum dolor',
                        url: 'assets/videos/free-courses-with-free-certificates.mp4',
                        read:false,
                        exercise: [
                          {
                            id: 1,
                            title: 'Exercise 1',
                            question1:'Lorem ipsum dolor?',
                            answer1: 'Lorem ipsum',
                            question2:'Lorem ipsum dolor?',
                            answer2: 'Lorem ipsum',
                            question3:'Lorem ipsum dolor?',
                            answer3: 'Lorem ipsum',
                            question4:'Lorem ipsum dolor?',
                            answer4: 'Lorem ipsum',
                            question5:'Lorem ipsum dolor?',
                            answer5: 'Lorem ipsum',
                          },
                        ],
                      },
                    ],
                  },
                ]
        }
    ];

export default CourseData;